ボスの範囲攻撃の当たり判定の追加
tricore-as03/3DActionGame pull request #1
Opened 2024-08-20 08:24 UTC by MisukizZ

・追加したもの
　・ボスが範囲攻撃をする際にShotを作成する処理
　・Shotを作成する際に必要なShotManager
　・Shotのアクティブ状態を管理するShotObjectPoolの作成
　・Shotの更新処理やCollisionManagerに当たり判定を送る処理

2024-08-21 08:42 UTC, tricore-as03 requested changes

2024-08-21 08:42 UTC, tricore-as03 commented on GameProject/GameProject/ShotManager.h
> +    void CreateShot(InitializeShotData initializeShotData);
[MUST]
`SpawnShot`がよいかと。
ショットを生成しているというよりかは、事前に生成されたショットを出現させているだけなので。

2024-08-21 08:42 UTC, tricore-as03 commented on GameProject/GameProject/BossAreaAttack.h
> +    static constexpr int   CreateShotNumber         = 50;           // 範囲攻撃で生成する弾の数
[MUST]
`SpawnShotCount`が良いかと。
変数名だけみたときに、`Number`だと生成された弾の識別番号なのかと勘違いしそうなので。
識別番号とかの単純な値はNumber、変動する可能性のある何らかの数を表すときはCountというような使い分けをするとよかいと思います。

2024-08-21 08:42 UTC, tricore-as03 commented on GameProject/GameProject/CollisionManager.h
> +    static void DeleteInstance();
[Q]
staticにする必要ありますかね？

2024-08-22 04:23 UTC, MisukizZ commented on GameProject/GameProject/ShotManager.h
> +    void CreateShot(InitializeShotData initializeShotData);
たしかに作成するじゃおかしかったです！
SpawnShotに修正しました！

2024-08-22 04:23 UTC, MisukizZ commented on GameProject/GameProject/BossAreaAttack.h
> +    static constexpr int   CreateShotNumber         = 50;           // 範囲攻撃で生成する弾の数
承知しました。SpawnShotCountに修正しました！
ありがとうございます！

2024-08-22 04:23 UTC, MisukizZ commented on GameProject/GameProject/CollisionManager.h
> +    static void DeleteInstance();
シングルトンクラスのインスタンスを全てMainで作成していて
その際にMainはシングルトンクラスにアクセスするポインタを取得していないので
削除する際も、作成する時と同じようにstatic関数を使用して削除するようにしていました。
static関数から通常関数に修正したほうがよいでしょうか？

2024-08-22 06:02 UTC, tricore-as03 commented on GameProject/GameProject/CollisionManager.h
> +    static void DeleteInstance();
なるほど、であれば、そのままで大丈夫です。

2024-08-22 06:06 UTC, tricore-as03 approved these changes
LGTM

2024-08-22 06:52 UTC, merged