ゲームが始まった際の演出の追加
tricore-as03/3DActionGame pull request #10
Opened 2024-08-20 08:57 UTC by MisukizZ

ゲーム開始時に入力を無効にして自動でプレイヤーを動かすようにし、プレイヤーとボスとの距離やアニメーションの状態によってカメラを移動させて登場シーンを作成しました。

ボスの登場シーンに使用するエフェクトを追加しました。

2024-08-30 10:08 UTC, tricore-as03 requested changes

2024-08-30 10:08 UTC, tricore-as03 commented on GameProject/GameProject/Boss.cpp
> +        SwtchAnimation();
[MUST]
誤字です。
`SwtchAnimation`→`SwitchAnimation`

2024-08-30 10:08 UTC, tricore-as03 commented on GameProject/GameProject/Player.cpp
> +    if (! isEndMove)
[MUST]
無駄なスペース入ってますね。

2024-09-03 04:34 UTC, MisukizZ commented on GameProject/GameProject/Boss.cpp
> +        SwtchAnimation();
申し訳ございません。
誤字修正いたしました。

2024-09-03 04:34 UTC, MisukizZ commented on GameProject/GameProject/Player.cpp
> +    if (! isEndMove)
気づいていませんでした。
こちらも修正いたしました。

2024-09-03 07:30 UTC, tr-t-mitsumaru approved these changes
LGTM

2024-09-03 07:35 UTC, merged