プレイヤーの行動の一部修正
tricore-as03/3DActionGame pull request #4
Opened 2024-08-20 08:36 UTC by MisukizZ

・回避中の無敵行動の追加
・回避中の移動を追加
・ガード時のダメージ軽減を追加
・プレイヤーの通常攻撃と強攻撃の差別化

2024-08-21 10:49 UTC, tricore-as03 requested changes

2024-08-21 10:49 UTC, tricore-as03 commented on GameProject/GameProject/Player.h
> +    };
[Q]
PlayerStateと別になってるのは何故でしょうか？
HitStateとDamged、NoLifeとDeadStateはそれぞれ同じだと思うのですが。

2024-08-21 10:49 UTC, tricore-as03 commented on GameProject/GameProject/PlayerDead.h
> +    PlayerDead(int InitalModelHandle, int beforeAnimationIndex);
[MUST]
変数は先頭小文字で

2024-08-22 08:59 UTC, MisukizZ commented on GameProject/GameProject/Player.h
> +    };
PlayerStateは現在nowStateの中身がどのステートなのかを判断するために使用していて、
HitStateはPlayerがOnHitでダメージを受けたことをステートにしらせて各ステートがHitStateをnewしてもらったり
HitStateが体力が0になった時にDeadStateに移行するために使用しています。

LifeStateとPlayerStateを分けたのは、それぞれで使用している役割が違うので分けた方が使いやすいかと思ったからです。
分かりづらい説明で申し訳ございません。

2024-08-22 08:59 UTC, MisukizZ commented on GameProject/GameProject/PlayerDead.h
> +    PlayerDead(int InitalModelHandle, int beforeAnimationIndex);
すみません！気づいてませんでした！
小文字に修正しました。

2024-08-23 01:28 UTC, tricore-as03 commented on GameProject/GameProject/Player.h
> +    };
`StateBase.OnDamage`が呼ばれた時点でダメージを受けたことが確定していると思うので、その関数の中で直接
```
// ダメージを受けていたらヒットステートに移行
    if (lifeState == Player::Damaged)
    {
        nextState = new PlayerHit(modelhandle, animationIndex, Player::Impact);
    }
    //アニメーションの再生が終了したらステートを切り替える
    else if (currentPlayAnimationState == FirstRoopEnd)
    {
        nextState = new PlayerIdle(modelhandle, this->GetAnimationIndex());

    }
    else
    {
        nextState = this;
    }
```
を実行してあげれば、LifeStateは不要になりませんか？
また、このプルリクですぐ修正できそうですかね？

2024-08-26 05:51 UTC, tricore-as03 requested changes

2024-08-26 05:51 UTC, tr-t-mitsumaru commented on GameProject/GameProject/PlayerDead.h
> +    PlayerDead(int InitalModelHandle, int beforeAnimationIndex);
他のクラスのほうで、`InitalModelHandle`が残っているので修正をお願いします。
命名修正の場合は、文字列の全体検索を行い、修正箇所が残ってないか確認をお願いします。

2024-08-28 03:02 UTC, MisukizZ commented on GameProject/GameProject/Player.h
> +    };
OnDamageの中で

// ヒットステートに切り替える
nextState = new PlayerHit(modelhandle, animationIndex, Player::Impact);
// ステートを切り替えたフラグを立てる
changedState = true;

の処理を行い各ステートのChangeStateでは

if( ! changedState)
{
         // ヒットステート以外のステート移行処理を書く
}

このように書くという認識でよいでしょうか？

2024-08-28 03:02 UTC, MisukizZ commented on GameProject/GameProject/PlayerDead.h
> +    PlayerDead(int InitalModelHandle, int beforeAnimationIndex);
確認が抜けていました。申し訳ございません。
再度、小文字に修正しました。

2024-08-28 09:18 UTC, tricore-as03 commented on GameProject/GameProject/Player.h
> +    };
はい、その認識であってます？
すぐ対応できそうですか？

2024-08-30 05:51 UTC, MisukizZ commented on GameProject/GameProject/Player.h
> +    };
申し訳ございません。遅くなりました。
上記の方法で修正を試してみたんですが、OnDamageでnewしてしまうとCollisionManagerのUpdateが呼ばれるタイミングでnexttStateがnewされるんですが、それだとPlayerのUpdateで前のステートをdeleteするので1フレームだけ両方のステートが残っている状態になるのですが、それはよいのでしょうか？

2024-08-30 08:53 UTC, tricore-as03 commented on GameProject/GameProject/Player.h
> +    };
問題ないです。
というか「1フレームだけ両方のステートが残っている状態になる」というのは間違いですね。
https://github.com/tricore-as03/3DActionGame/blob/main/GameProject/GameProject/Game.cpp#L32
今回の実装の場合だと、Game.Updateのwhileの１ループで１フレームとなります。
なので、CollisionManagerとPlayerのどちらのUpdateも１フレーム内での処理です。

2024-09-02 04:25 UTC, MisukizZ commented on GameProject/GameProject/Player.h
> +    };
ありがとうございます！LifeStateを削除する形でOnDamageで直接HitStateをnewするように修正しました。

2024-09-02 04:32 UTC, tricore-as03 approved these changes
LGTM

2024-09-02 04:35 UTC, merged