ボスのAIの追加
tricore-as03/3DActionGame pull request #5
Opened 2024-08-20 08:40 UTC by MisukizZ

プレイヤーとの距離によって選ばれる行動パターンが変わり、その中からランダムで選ばれるようにしました。

2024-08-23 02:42 UTC, tricore-as03 approved these changes
LGTM

2024-08-28 06:03 UTC, tricore-as07 requested changes

2024-08-28 06:03 UTC, tr-k-orimoto commented on GameProject/GameProject/BossAreaAttack.cpp
> +    if (currentPlayAnimationState == FirstRoopEnd)
[Q]
RoopはLoopの間違いじゃないですかね？

2024-08-28 06:03 UTC, tr-k-orimoto commented on GameProject/GameProject/BossIdle.cpp
> +
本来はこういう無駄な空白は消した方がいいです

2024-08-28 06:03 UTC, tr-k-orimoto commented on GameProject/GameProject/BossIdle.cpp
> +        nextState = new BossDefaultAttack(modelhandle, animationIndex);
[MUST]
こういう複数行ある処理をインデントだけして{}で囲んでいないものはコーディングルール違反です

2024-08-28 06:03 UTC, tr-k-orimoto commented on GameProject/GameProject/BossIdle.cpp
> +        if (targetDistance <= ShortRange)
このあたりはネストが深すぎるので
関数化するなりしたほうがいいと思います

2024-08-28 06:03 UTC, tr-k-orimoto commented on GameProject/GameProject/BossIdle.h
> +    enum  NextStateList
[MUST]
enumでListという命名は誤解を生むので使うべきではないですね

また、Nextが含まれていますが今のステート管理は別のenumでやっている感じでしょうか？

2024-08-28 06:03 UTC, tr-k-orimoto commented on GameProject/GameProject/BossMove.h
>      //AIを作成したら入力は必要ないので削除
[Q]
AIの追加PRですがここは必要あるのでしょうか？

2024-08-28 06:03 UTC, tricore-as07 commented on GameProject/GameProject/BossStart.cpp
>      //ToDo
[MUST]
おそらくこのTODOコメントはもう不要だと思うのでちゃんと消しましょう

2024-08-28 06:03 UTC, tricore-as07 commented on GameProject/GameProject/BossStart.h
> +        SitDown      = 0,  //座っている
一応SitDownは座っているという状態を表しているわけではなく
座るという動作を表す動詞ですね

2024-08-28 06:03 UTC, tricore-as07 commented on GameProject/GameProject/Player.h
> +    bool          isDamage;         // ダメージを受けたかのフラグ
[MUST]
isDamageは「ダメージを受けたか」という意味ではなく
「ダメージかどうか」になるので意味が異なります

2024-09-02 05:01 UTC, MisukizZ commented on GameProject/GameProject/BossAreaAttack.cpp
> +    if (currentPlayAnimationState == FirstRoopEnd)
申し訳ございません。Loopの間違いです！修正しました。

2024-09-02 05:01 UTC, MisukizZ commented on GameProject/GameProject/BossIdle.cpp
> +
申し訳ございません。削除しました。
今後気づき次第削除していきます。

2024-09-02 05:01 UTC, MisukizZ commented on GameProject/GameProject/BossIdle.cpp
> +        nextState = new BossDefaultAttack(modelhandle, animationIndex);
承知しました。とりあえずこのプルリクエストの分だけ修正しました。
他の部分はそのプルリクエストで修正していきます。

2024-09-02 05:01 UTC, MisukizZ commented on GameProject/GameProject/BossIdle.cpp
> +        if (targetDistance <= ShortRange)
承知しました。whileの中身を関数化しました。

2024-09-02 05:01 UTC, MisukizZ commented on GameProject/GameProject/BossIdle.h
> +    enum  NextStateList
確かに安易にリストという言葉を使用していました。そもそも前のステートと次のステート両方の管理に使用しているのでNextStateという名前自体がおかしかったので、IdleStateに関連するステートたちという意味でIdleStateRelatedStatesに変更したのですが、問題ないでしょうか？

2024-09-02 05:01 UTC, MisukizZ commented on GameProject/GameProject/BossMove.h
>      //AIを作成したら入力は必要ないので削除
MoveSpeedとMoveFrameLimitはボスのAIを追加して初めて移動をさせたので必要だったのですが、アニメーションスピードなどは元々あった部分を定数化しただけなのでこのプルリクで行うべきではなかったです。

2024-09-02 05:01 UTC, MisukizZ commented on GameProject/GameProject/BossStart.cpp
>      //ToDo
申し訳ございません。削除いたしました。

2024-09-02 05:01 UTC, MisukizZ commented on GameProject/GameProject/BossStart.h
> +        SitDown      = 0,  //座っている
確かにそうでした！SitDownではなくSittingに修正しました。

2024-09-02 05:01 UTC, MisukizZ commented on GameProject/GameProject/Player.h
> +    bool          isDamage;         // ダメージを受けたかのフラグ
確かに意味がおかしかったです。ただ、確認したらisDamageをそもそも使用していなかったので削除する形で修正しようと思います。もし命名を修正する場合はダメージを受けたという意味でtookDamageなどでよいのでしょうか？

2024-09-02 06:50 UTC, MisukizZ commented on GameProject/GameProject/BossIdle.h
> +    enum  NextStateList
Stateの管理なのでIdleに持たせるのではなくBossに持たせた方がいいのでBossに移行させて名前をBossActionStateに変更しました。

2024-09-02 06:50 UTC, MisukizZ commented on GameProject/GameProject/BossMove.h
>      //AIを作成したら入力は必要ないので削除
Todoコメントの削除忘れの修正を行いました。

2024-09-02 06:53 UTC, tr-k-orimoto approved these changes
LGTM

2024-09-02 06:54 UTC, merged