プレイヤーの攻撃処理の修正
tricore-as03/3DActionGame pull request #6
Opened 2024-08-20 08:44 UTC by MisukizZ

・ボスと当たった際の押し戻し処理の追加
・プレイヤーの攻撃を連続攻撃に変更
・プレイヤーのショットの追加

2024-08-26 05:58 UTC, tricore-as03 requested changes

2024-08-26 05:58 UTC, tricore-as03 commented on GameProject/GameProject/CollisionManager.cpp
> +                collider->onHit(*target);
[Q]
`target`側のonHitを呼ぶのを忘れてませんか？

2024-09-03 02:00 UTC, MisukizZ commented on GameProject/GameProject/CollisionManager.cpp
> +                collider->onHit(*target);
当たり判定の更新を多重ループで行っているので、この段階でのtarget側がcollider側になった際にOnHitを呼ぶ形にしています。

2024-09-03 02:42 UTC, tricore-as03 approved these changes

2024-09-03 02:42 UTC, tricore-as03 commented on GameProject/GameProject/PlayerAttack.h
> +    static constexpr float  ThirdAttackCollisionEndTime              = 0.84f;  // 3撃目の当たり判定を終了する時間
[IMO]
`FirstXXX`や`SecondXXX`のように連番で複数用意するのではなく、ひとつ分のデータを格納するクラスを作り、そのクラス自体をリストや配列で複数用意するのが良いです。

```
class AttackData
{
    float ComboMoveSpeed;
    float AttackCollisionStartTime;
    float AttackCollisionEndTime;
}
```
命名は仮ですが、今回の場合だと、攻撃ひとつ分のデータクラスを用意して、それをリストや配列で複数用意するのが良さそうです。
このプルリクで修正してほしいですが必須ではないです。

2024-09-03 02:43 UTC, tricore-as03 commented on GameProject/GameProject/CollisionManager.cpp
> +                collider->onHit(*target);
把握です。

2024-09-03 04:13 UTC, MisukizZ commented on GameProject/GameProject/PlayerAttack.h
> +    static constexpr float  ThirdAttackCollisionEndTime              = 0.84f;  // 3撃目の当たり判定を終了する時間
承知いたしました！連続して書いている部分を構造体に修正いたしました。

2024-09-03 04:34 UTC, tricore-as03 approved these changes
LGTM

2024-09-03 04:38 UTC, merged