プレイヤーのショットのエフェクトと当たった際のエフェクトを追加
tricore-as03/3DActionGame pull request #9
Opened 2024-08-20 08:54 UTC by MisukizZ

追加したもの
・プレイヤーの弾自体のエフェクト
・撃つ際のエフェクト
・当たった際のエフェクト

2024-08-30 10:01 UTC, tricore-as03 requested changes

2024-08-30 10:01 UTC, tricore-as03 commented on GameProject/GameProject/Boss.cpp
> +    float angle = atan2(direction.x, direction.z);
[MUST]
２つのベクトルから角度を算出する関数を用意して共通化したいですね。

2024-09-03 04:29 UTC, MisukizZ commented on GameProject/GameProject/Boss.cpp
> +    float angle = atan2(direction.x, direction.z);
確かに共通化したほうが良かったです！
Utilityに関数を作成し共通化させました。

2024-09-03 04:38 UTC, tricore-as03 approved these changes
LGTM

2024-09-03 04:43 UTC, merged